---

- user:
    name: authentik
    create_home: true
    groups: docker
    append: true
    shell: /bin/bash
    system: true
  register: authentik_user

- ansible.builtin.set_fact:
    authentik_uid: "{{ authentik_user.uid }}"

- file:
    path: "{{ item }}"
    owner: authentik
    group: authentik
    state: directory
  loop:
    - /home/authentik/authentik
    - /home/authentik/authentik/certs
    - /home/authentik/authentik/custom-templates
    - /home/authentik/authentik/data

- template:
    src: docker-compose.yml.j2
    dest: /home/authentik/authentik/docker-compose.yml
    owner: authentik
    group: authentik
  notify: restart-authentik

- template:
    src: env.j2
    dest: /home/authentik/authentik/.env
    owner: authentik
    group: docker
    mode: '0640'
  notify: restart-authentik

- template:
    src: authentik.service.j2
    dest: /etc/systemd/system/authentik.service
  register: authentik_service
  notify: restart-authentik

- shell:
    cmd: systemctl daemon-reload
  when: authentik_service.changed

- service:
    name: authentik
    enabled: yes
    state: started

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
