---

- deb822_repository:
    name: mattermost
    types: deb
    uris: https://deb.packages.mattermost.com
    suites: '{{ ansible_distribution_release }}'
    components: main
    architectures: amd64
    signed_by: https://deb.packages.mattermost.com/pubkey.gpg

- apt:
    name: mattermost
    update_cache: true
    state: present

- ansible.builtin.shell:
    cmd: cp /opt/mattermost/config/config.defaults.json /opt/mattermost/config/config.json
    creates: /opt/mattermost/config/config.json

- ansible.builtin.slurp:
    src: /opt/mattermost/config/config.json
  register: mm_config_raw

- ansible.builtin.set_fact:
    mm_config: "{{ mm_config_raw.content | b64decode | from_json | combine(config, recursive=True) }}"

- ansible.builtin.copy:
    dest: /opt/mattermost/config/config.json
    owner: mattermost
    group: mattermost
    mode: '0600'
    content: "{{ mm_config | to_nice_json(ensure_ascii=False, indent=4, preprocess_unsafe=False, sort_keys=False) }}"
  notify: restart-mattermost

- service:
    name: mattermost
    enabled: yes
    state: started

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
