FROM node:21-alpine3.19 AS build

WORKDIR /tmp/taiga-contrib-oidc-auth
COPY --chown=taiga:taiga ./taiga-contrib-oidc-auth/front /tmp/taiga-contrib-oidc-auth

RUN npm install
RUN npx gulp build

FROM ghcr.io/fabianmp/taiga-front:{{ taiga_versions.front }}-fabianmp.0.1.0

COPY --from=build --chown=taiga:taiga /tmp/taiga-contrib-oidc-auth/dist /usr/share/nginx/html/plugins/oidc-auth
