---
- apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    update_cache: yes
    state: present

- apt:
    name: grafana
    state: present

- template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
  notify: restart-grafana

- service:
    name: grafana-server
    enabled: yes
    state: started

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
