---
- name: Install dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Trust apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add mssql repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_facts['distribution_version'] }}/mssql-server-2019 {{ ansible_facts['distribution_release'] }} main"
    state: present

- name: Add prod repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_facts['distribution_version'] }}/prod {{ ansible_facts['distribution_release'] }} main"
    state: present

- name: Install Azure CLI
  apt:
    pkg:
      - mssql-server
      - mssql-tools
      - unixodbc-dev
    state: latest

- name: Add mssql-tools to path
  copy:
    dest: /etc/profile.d/mssql-tools.sh
    content: "PATH=\"${PATH}:/opt/mssql-tools/bin/\"\n"

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
