---

site_name: proxy
proxy_host: localhost
proxy_port: 8080
proxy_use_https: false
proxy_trust_https: false
proxy_port_http: 0
server_name: "{{ ansible_facts['fqdn'] }}"
server_port: 443
allow_http: false

proxy_paths: {}

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
