---
- hosts: all
  tags: ssh
  roles:
    - role: ssh
      tags: ssh

    - role: ssh-keys
      tags: ssh-keys

    - role: tls
      tags: tls


- hosts: work
  tags: ssh
  roles:
    - role: ssh-keys
      tags: ssh-keys
      ssh_user: tom


- hosts: all
  tags: common

  roles:
    - role: fail2ban
      tags: fail2ban

  tasks:
    - ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - debian-archive-keyring
          - debian-keyring
          - gpg
          - gnupg-agent
          - htop
          - iftop
          - moreutils
          - mosh
          - mtr-tiny
          - net-tools
          - pwgen
          - python3
          - python3-debian
          - python3-pip
          - rsync
          - software-properties-common
          - sudo
          - telnet
          - tree
          - unzip
          - vim
          - wget
        state: present

    - ansible.builtin.lineinfile:
        path: /etc/locale.gen
        line: "en_US.UTF-8 UTF-8"
      register: locale_gen

    - ansible.builtin.shell:
        cmd: locale-gen
      when: locale_gen.changed

    - ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "^\\s*\\w+\\s+requiretty"
        state: absent
      tags: sudo

    - ansible.builtin.file:
        path: /root/bin
        mode: '0755'
        state: directory


- hosts: vm
  tags:
    - qemu
    - vm
  tasks:
    - ansible.builtin.apt:
        name: qemu-guest-agent
        state: present

    - ansible.builtin.service:
        name: qemu-guest-agent
        enabled: yes
        state: started

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
