---
- hosts: influxdb
  roles:
    - role: letsencrypt-certs
      tags: letsencrypt-certs

    - role: influxdb
      tags: influxdb

    - role: nginx
      tags: nginx
      proxy_host: "{{ ansible_facts['fqdn'] }}"
      proxy_port: 8086
      proxy_ssl: yes

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
