---
- file:
    path: /root/plausible
    state: directory

- template:
    src: compose.yml.j2
    dest: /root/plausible/docker-compose.yml

- template:
    src: plausible.env.j2
    dest: /root/plausible/plausible-conf.env

- shell:
    cmd: docker-compose up --detach
    chdir: /root/plausible

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
