---
- ansible.builtin.assert:
    that:
      - apcupsd_mode != ""
      - apcupsd_mode in valid_modes
      - apcupsd_port > 0
      - ups_name != ""

- ansible.builtin.apt:
    name:
      - apcupsd
      - apcupsd-doc
      - ucspi-tcp
    state: present

- ansible.builtin.copy:
    src: usvnutwrapper.sh
    dest: /usr/local/bin/usvnutwrapper.sh
    mode: '0755'
  register: nutwrapper_script

- ansible.builtin.template:
    src: nutwrapper.service.j2
    dest: /etc/systemd/system/nutwrapper.service
  register: nutwrapper_service

- ansible.builtin.shell:
    cmd: systemd daemon-reload
  when: nutwrapper_service.changed

- ansible.builtin.service:
    name: nutwrapper
    state: restarted
  when:
    - nutwrapper_script.changed or nutwrapper_service.changed
    - apcupsd_mode == 'standalone'

- ansible.builtin.include_tasks:
    file: "{{ apcupsd_mode }}.yml"

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
