---

- ansible.builtin.deb822_repository:
    name: openproject
    types: deb
    uris: "https://dl.packager.io/srv/deb/opf/openproject/stable/{{ openproject_version }}/{{ ansible_facts['distribution'] | lower }}"
    suites: "{{ openproject_apt_suite }}"
    components: main
    architectures: amd64
    signed_by: https://dl.packager.io/srv/opf/openproject/key

- ansible.builtin.apt:
    name:
      - memcached
      - openproject
    update_cache: true
    state: present

- ansible.builtin.template:
    src: installer.dat.j2
    dest: /etc/openproject/installer.dat
    owner: openproject
    group: openproject
    mode: '0640'
  notify: configure-openproject

- ansible.builtin.copy:
    src: enterprise_token.rb
    dest: /opt/openproject/app/models/enterprise_token.rb
    owner: root
    group: openproject
    mode: '0644'
  notify: restart-openproject

- ansible.builtin.service:
    name: openproject
    enabled: yes
    state: started

# vim: set ft=yaml ts=2 sts=2 sw=2 et:
